version: '3'

services:
  user-container:
    image: user-service:latest
    ports:
      - "8081:8081"
    environment:
      DB_IP: mysqldb-users-container
      DB_PORT: "3306"
      DEVICE_DOMAIN: device-container
    depends_on:
      - mysqldb-users-container
    networks:
      - springboot-mysql-net

  device-container:
    image: device-service:latest
    ports:
      - "8082:8082"
    environment:
      DB_IP: mysqldb-devices-container
      DB_PORT: "3306"
      RABBIT_DOMAIN: rabbitMQ-container
    depends_on:
      - mysqldb-devices-container
    networks:
      - springboot-mysql-net

  monitoring-container:
    image: monitoring-service:latest
    ports:
      - "8083:8083"
    environment:
      DB_IP: mysqldb-monitoring-container
      DB_PORT: "3306"
      RABBIT_DOMAIN: rabbitMQ-container
    depends_on:
      - mysqldb-monitoring-container
      - rabbitMQ-container
      - device-container
    networks:
      - springboot-mysql-net

  chat-container:
    image: chat-service:latest
    ports:
      - "8084:8084"
    depends_on:
      - device-container
      - user-container
    networks:
      - springboot-mysql-net

  mysqldb-users-container:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: ds_2023_users
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'
    networks:
      - springboot-mysql-net

  mysqldb-devices-container:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: ds_2023_devices
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'
    networks:
      - springboot-mysql-net

  mysqldb-monitoring-container:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: ds_2023_monitoring
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'
    networks:
      - springboot-mysql-net

  front-container:
    image: frontend-service:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - user-container
      - device-container
    networks:
      - springboot-mysql-net

  rabbitMQ-container:
    image: rabbitmq:3.13.0-rc.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge

#  mysqldb-container:
#    image: mysql:latest
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_PASSWORD: 12345678
#      MYSQL_ROOT_PASSWORD: 12345678
#      MYSQL_ROOT_HOST: '%'
#    networks:
#      - springboot-mysql-net

#  docker run -p 3306:3306 --name mysqldb --network springboot-mysql-net -e MYSQL_ROOT_PASSWORD=12345678
#  -e MYSQL_DATABASE=ds_2023_devices -e MYSQL_PASSWORD=12345678 -d mysql:latest

#    docker run -p8081:8081 --name use_container
#    --network=springboot-mysql-net -e DEVICE_SERVER_URL=device_container -d user_service:latest