services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: ds_2023_users
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'

  tomcat-db-api:
    image: user_service
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
